### ISSUE TITLE
✨ [FEATURE] Organization 비즈니스 로직 구현

### ISSUE THREAD

**Issue by oxdjww** [Team-OnDot/OnDot-Backend#6]
# Title
- Organization 도메인 구현

# TODO
- [x] 그룹 정보 조회
- [x] ~~그룹 설정 조회~~ **(그룹 정보 조회랑 동일)**
- [x] 그룹 설정 변경

# etc
-
